import { useMemo } from "react";

function useServices(){
    return useMemo(() => [
        {
            id: "1",
            animal_type: "Ev Hayvanları",
            main_category: "Muayene ve Klinik İşlemler",
            operation_category: "Muayene ve Konsültasyonlar",
            operation_name: "Muayene",
            operation_note: "",
            costs: {cat: 750, dog: 750},
        },
        {
            id: "2",
            animal_type: "Ev Hayvanları",
            main_category: "Muayene ve Klinik İşlemler",
            operation_category: "Muayene ve Konsültasyonlar",
            operation_name: "Kontrol",
            operation_note: "Daha önce tedavisi yapılan",
            costs: {cat: 400, dog: 400},
        },
        {
            id: "3",
            animal_type: "Ev Hayvanları",
            main_category: "Muayene ve Klinik İşlemler",
            operation_category: "Muayene ve Konsültasyonlar",
            operation_name: "Muayene",
            operation_note: "Çalışma saatleri dışı",
            costs: {cat: 1200, dog: 1200},
        },
        {
            id: "4",
            animal_type: "Ev Hayvanları",
            main_category: "Görüntüleme ve İleri Tanı Yöntemleri",
            operation_category: "Radyografi",
            operation_name: "Röntgen Film",
            operation_note: "13x18 ve 18x24",
            costs: {cat: 750, dog: 750},
        },
        {
            id: "5",
            animal_type: "Ev Hayvanları",
            main_category: "Görüntüleme ve İleri Tanı Yöntemleri",
            operation_category: "Ürolojik Radyografi",
            operation_name: "Üretrogram",
            operation_note: "",
            costs: {cat: 1200, dog: 1200},
        },
        {
            id: "6",
            animal_type: "Ev Hayvanları",
            main_category: "Cerrahi Girişimler",
            operation_category: "Anestezi, Sedasyon ve Operasyona Hazırlık Uygulamaları",
            operation_name: "Lokal Anestezi",
            operation_note: "",
            costs: {cat: 600, dog: 600},
        },
        {
            id: "6",
            animal_type: "Ev Hayvanları",
            main_category: "Cerrahi Girişimler",
            operation_category: "Anestezi, Sedasyon ve Operasyona Hazırlık Uygulamaları",
            operation_name: "Lokal Anestezi",
            operation_note: "",
            costs: {cat: 600, dog: 600},
        },
        {
            id: "6",
            animal_type: "Ev Hayvanları",
            main_category: "Cerrahi Girişimler",
            operation_category: "Anestezi, Sedasyon ve Operasyona Hazırlık Uygulamaları",
            operation_name: "Lokal Anestezi",
            operation_note: "",
            costs: {cat: 600, dog: 600},
        },
        {
            id: "6",
            animal_type: "Ev Hayvanları",
            main_category: "Cerrahi Girişimler",
            operation_category: "Anestezi, Sedasyon ve Operasyona Hazırlık Uygulamaları",
            operation_name: "Lokal Anestezi",
            operation_note: "",
            costs: {cat: 600, dog: 600},
        },
        {
            id: "6",
            animal_type: "Ev Hayvanları",
            main_category: "Cerrahi Girişimler",
            operation_category: "Anestezi, Sedasyon ve Operasyona Hazırlık Uygulamaları",
            operation_name: "Lokal Anestezi",
            operation_note: "",
            costs: {cat: 600, dog: 600},
        },
        {
            id: "6",
            animal_type: "Ev Hayvanları",
            main_category: "Cerrahi Girişimler",
            operation_category: "Anestezi, Sedasyon ve Operasyona Hazırlık Uygulamaları",
            operation_name: "Lokal Anestezi",
            operation_note: "",
            costs: {cat: 600, dog: 600},
        },
        {
            id: "6",
            animal_type: "Ev Hayvanları",
            main_category: "Cerrahi Girişimler",
            operation_category: "Anestezi, Sedasyon ve Operasyona Hazırlık Uygulamaları",
            operation_name: "Lokal Anestezi İstikametçiler dolayısıyla Anestezi Lokal Anestezi",
            operation_note: "",
            costs: {cat: 600, dog: 600},
        },
    ], []);
}

export default useServices;